package com.yigwoo.simple.persistence;

import com.yigwoo.simple.domain.Account;

/**
 * AccountMapper is a standard Data Acess Object interface which
 * takes advantage of Spring Data JPA framework. The implementation
 * file is auto generated by Spring Data JPA framework.
 * For more infos, consult the reference manual of Spring Data JPA
 * @author YigWoo
 *
 */

public interface AccountMapper {
	public void insertAccount(Account account);

	public void updateAccount(Account account);

	public void deleteAccountById(int id);

	public Account getAccountById(int id);

	public Account getAccountByUsername(String username);

	public Account getAccountByEmail(String email);

}
