package com.yigwoo.repository;

import java.util.List;

import org.springframework.data.repository.Repository;

import com.yigwoo.entity.User;

/**
 * UserDao is a standard Data Acess Object interface which
 * takes advantage of Spring Data JPA framework. The implementation
 * file is auto generated by Spring Data JPA framework.
 * For more infos, consult the reference manual of Spring Data JPA
 * @author YigWoo
 *
 */

public interface UserDao extends Repository<User, Long> {
	public User save(User user);
	public void delete(User user);
	public void delete(Long id);
	public User findOne(Long id);
	public List<User> findAll();
	public List<User> findByRoles(String roles);
	public User findByUsername(String username);
	public User findByEmail(String email);
}


