package com.yigwoo.repository;

import org.springframework.data.repository.Repository;
import com.yigwoo.entity.User;

/**
 * UserDao is a standard Data Acess Object interface which
 * takes advantage of Spring Data JPA framework. The implementation
 * file is auto generated by Spring Data JPA framework.
 * For more infos, consult the reference manual of Spring Data JPA
 * @author YigWoo
 *
 */

public interface UserDao extends Repository<User, Long> {
	public User save(User user);
	public User findOne(Long id);
	public User findByUsername(String username);
	public User findByEmail(String email);
}


